spark.master                              spark://spark-master:7077
spark.eventLog.enabled                    true
spark.eventLog.dir                        file:///tmp/spark-events
spark.sql.shuffle.partitions              200
spark.sql.streaming.checkpointLocation    /tmp/spark-checkpoints/default
spark.sql.streaming.stateStore.maintenanceInterval 60s
spark.sql.adaptive.enabled                true
spark.serializer                          org.apache.spark.serializer.KryoSerializer
spark.driver.extraJavaOptions             -Dlog4j2.formatMsgNoLookups=true
spark.executor.extraJavaOptions           -Dlog4j2.formatMsgNoLookups=true
spark.jars.packages                       org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
spark.jars.ivy                            /tmp/.ivy2
