FROM python:3.11-slim

WORKDIR /app

COPY api/fastapi/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY api/fastapi/app ./app
COPY ml/artifacts ./ml/artifacts

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
